### ISSUE TITLE
Emailing does not work with sendmail

### ISSUE THREAD

**Issue by woopstar** [dotmanila/pyxbackup#10]
When emailing is enabled and sendmail is the only installed option, the script fails with the following error:

```
Traceback (most recent call last):
  File "./pyxbackup", line 2619, in <module>
    traceback.format_exc())
  File "./pyxbackup", line 924, in _notify_by_email
    s = smtplib.SMTP('127.0.0.1')
  File "/usr/lib/python2.7/smtplib.py", line 251, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/lib/python2.7/smtplib.py", line 311, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/lib/python2.7/smtplib.py", line 286, in _get_socket
    return socket.create_connection((host, port), timeout)
  File "/usr/lib/python2.7/socket.py", line 571, in create_connection
    raise err
socket.error: [Errno 111] Connection refused
```

Consider to do a sanity check first or use build in mailer daemon instead of connecting to localhost?

**Comment by dotmanila** [comment]
@woopstar is your sendmail not running as an MTA abd only used as binary? I might extend better email delivery options in the future but for now, as much as possible to use what generally works and reduce the external dependencies of the script.

However, I added initial email validation, when notify_by_email or notify_on_success is configured, mail delivery will be tested one time and a status file will be stored on STOR_DIR on success, if not the script will fail. This has been added on latest commit.
