### ISSUE TITLE
No incremental backup, do full backup

### ISSUE THREAD

**Issue by woopstar** [dotmanila/pyxbackup#12]
If you do a incremental backup, but there is a no full backup it should simply just do a full backup

**Comment by woopstar** [comment]
I just reconsidered this issue. Maybe exit with different exit code, so you're able to restart the process in full mode instead?

**Comment by dotmanila** [comment]
I've defined more clearer exit codes moving forward so it is more scriptable i.e. if XB_EXIT_NO_FULL code is returned, you can start a full backup.
