### ISSUE TITLE
Exit codes are not set upon exception

### ISSUE THREAD

**Issue by woopstar** [dotmanila/pyxbackup#15]
```
_die("An exception error has occurred!")
```

Is put into the

```
except Exception, e:
```

Block in the bottom. As this function raises an exception, this causes an infinite exception loop.

Suggestion:

Change `_die` to `_error` and add the following to the exception block too:

```
sys.exit(xb_exit_code)
```

**Comment by dotmanila** [comment]
Latest commit have this in place. Thanks @woopstar!
