### ISSUE TITLE
Full restore

### ISSUE THREAD

**Issue by NoodlesNZ** [dotmanila/pyxbackup#19]
It looks like when doing a restore of a full backup pyxbackup runs:
`innobackupex --apply-log --use-memory=128M --redo-only ...`
as well as
`innobackupex --apply-log --use-memory=128M ...`

Wouldn't it be quicker to just --apply-log for full restores? I assume (my python-fu is not very strong) that it does the --redo-only on the full backup to prepare for merging with an incremental.

**Comment by dotmanila** [comment]
@NoodlesNZ check the latest version, I've merged the last apply-log and redo-only. This means if you are restoring a full backup, it will only be one step, if restoring an incremental where will be no additional finalize step.
