### ISSUE TITLE
 ERROR: Remote command failed 

### ISSUE THREAD

**Issue by timxd** [dotmanila/pyxbackup#23]
Did a remote incremental backup,but got error:

ERROR: Remote command failed "bash: pyxbackup: command not found, CMD_FAIL"

Buy the way
In the /etc/pyxbackup.cnf
ssh_opts = "-i /home/revin/.ssh/id_rsa" should be ssh_opts = -i /home/revin/.ssh/id_rsa

**Comment by dotmanila** [comment]
@timxd use the remote_script option to point to the correct pyxbackup command on remote server. By the way, pyxbackup needs to run on the local server you are backing up from - though it can also be triggered remotely.
