### ISSUE TITLE
Broken binlog-stream cannot resume

### ISSUE THREAD

**Issue by dotmanila** [dotmanila/pyxbackup#35]
When binlog stream breaks and oldest backup's binary log coordinates has since been purged, resuming binlog stream will fail. This can usually be fixed by forcing a first binlog name to stream from though the cycle would simply continue.

- Add an option to simply continue where we left off even if the oldest backup's binlog does not exist anymore.
- The option would be like binlog-resume with values
  - 0 old behavior, abort
  - 1 if last binlog from backups still exists from the server, resume from there, otherwise abort
  - 2 if last binlog from backups does not exist from server, start from the first binlog on the server automatically, warn about gaps (how?)
- Warn if the oldest backup's binlog does not exist anymore.

**Comment by markusalbe** [comment]
What about detection of RESET MASTER... like when binlog numbering sequence goes back to zero.?
Also, --first-binlog does not seems to work when given as an option in the pyxbackup.cnf file

**Comment by dotmanila** [comment]
@markusalbe I suppose that is another special case we need to add to the list.

**Comment by dotmanila** [comment]
All fixed in 0.5, use `--binlog-resume=1` for additional checks and determine best binlog filename to stream from.
