### ISSUE TITLE
Featurerequest: get --help uptodate

### ISSUE THREAD

**Issue by hkheso** [dotmanila/pyxbackup#39]
./pyxbackup --config pyxbackup.cnf --help
Usage: pyxbackup [options] COMMAND
...
Valid commands are:

    full: Execute full backups
    incr: Execute incremental backups
    list: List existing backups and additional information
    status: Check status of last backup
    apply-last: Prepare to the most recent backup
    restore-set: Restore to a specific backup set
    last-lsn: Print out to_lsn value of last backup for incremental use
    wipeout: Cleanup all existing backups

It doesn't mention the binlog-stream command
 ./pyxbackup --config pyxbackup.cnf  binlog-stream
probably other things too?

**Comment by dotmanila** [comment]
Thanks for the report, fixed on latest commit.
