### ISSUE TITLE
pyxbackup + zabbix

### ISSUE THREAD

**Issue by hellracer** [dotmanila/pyxbackup#40]
Hi Jervin,

pyxbackup can't use on zabbix-agent  as a userParameter because when invoke in zabbix emits other extra stuff e.g

This seems harmless directly executing in the shell

root@db03:/etc/zabbix/zabbix_agentd.d# pyxbackup list | awk '{ print $4 }'
2017_11_03-07_23_35

Zabbix-Agent UserParameter
UserParameter=backup.datetime,pyxbackup list | awk '{ print $$4 }'

On Zabbix Server 

The data looks like this
[11/03/2017 07:17:10] WARN: Some files inside /data/bkp/stor were not recognized as either complete or an actual backup directory.

Best,

Ronald

**Comment by hellracer** [comment]
The workaround for this is basically run the zabbix-agent as a root, please closed

**Comment by dotmanila** [comment]
Ronald,

You need not run pyxbackup as root, any user will do as long as it has permission to read the backup files.
