### ISSUE TITLE
Missing store and work directory

### ISSUE THREAD

**Issue by woopstar** [dotmanila/pyxbackup#8]
The store directory and work directory should be created if missing instead of crashing program with exception.

**Comment by dotmanila** [comment]
IMHO, these values are first class directories i.e. not basedir where we can assume to just create them. Users can chose to put them no different volumes i.e. local, SAN, NFS, etc for different purposes thus I've decided to keep them explicitly required.

I would like to hear your thoughts on why you think we should be creating them automatically though.
