### ISSUE TITLE
extra_ibx_options with quotes fails

### ISSUE THREAD

**Issue by woopstar** [dotmanila/pyxbackup#9]
If you use the provided example of pyxbackup.cnf file, the backup fails.

extra_ibx_options contains quotes arround its extra options, but these quotes are passed to the innobackupex command which causes it to fail.

Script should remove single and double quotes before adding options

**Comment by dotmanila** [comment]
The reason this option includes the quotes is that there are options like --include=REGEXP that will explicitly require quoted values.

Updated documentation instead :)
